-- 001_create_audit_table.sql
-- Tabla ligera para auditoría de operaciones

create table if not exists audit_log (
   id         number generated by default on null as identity primary key,
   table_name varchar2(128),
   operation  varchar2(10),
   pk_value   varchar2(4000),
   changed_by varchar2(128),
   changed_at timestamp default systimestamp,
   details    clob
);

-- NOTE: Oracle 12c+ doesn't support IF NOT EXISTS for CREATE TABLE; if you need
-- compatibility, use a conditional PL/SQL block. Below is a PL/SQL safe create block.

-- BEGIN
--   EXECUTE IMMEDIATE 'CREATE TABLE AUDIT_LOG (
--     id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
--     table_name VARCHAR2(128),
--     operation VARCHAR2(10),
--     pk_value VARCHAR2(4000),
--     changed_by VARCHAR2(128),
--     changed_at TIMESTAMP DEFAULT SYSTIMESTAMP,
--     details CLOB
--   )';
-- EXCEPTION
--   WHEN OTHERS THEN
--     IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
-- END;
-- /